[package]
name = "az"
version = "0.1.0"
authors = ["you <you@example.com>"]

[dependencies]
hyper = "0.10"
encoding = "0.2"
rand = "0.3"
rustc-serialize = "0.3"
regex = "0.2"
clap = "2.20.0"
log = "0.3.6"
